import Head from "next/head";
import React from "react";
import LazyLoadImage from "../components/LazyLoadImage";

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Liên hệ | Nguyễn Hữu Trọng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contacts">
        <div className="contacts__wrapper">
          <div className="contacts__heading">
            <div className="contacts__title dark:text-slate-200">
              Liên hệ tôi:
            </div>
            <p className="contacts__description dark:text-slate-200">
              Tên: Nguyễn Hữu Trọng
            </p>
            <p className="contacts__description dark:text-slate-200">
              Email: huutrong1101@gmail.com
            </p>
            <p className="contacts__description dark:text-slate-200">
              Phone: 0773696410
            </p>
          </div>
          <figure className="contacts__image relative pb-[64.3836%]">
            <LazyLoadImage
              photo="https://res.cloudinary.com/dxkosumln/image/upload/v1675838654/profiles/trugf5ht9ser8dhtbtix.jpg"
              blurhash="LKF#|0~B^l9|.TbZaxxbyDI:xWoM"
              alt="alt"
            />
          </figure>
        </div>
      </div>
    </>
  );
};

export default Contacts;
