import Head from "next/head";
import React from "react";
import PeopleGrid from "../components/PeopleGrid";

const Intro = () => {
  return (
    <>
      <Head>
        <title>Giới thiệu | Nguyễn Hữu Trọng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PeopleGrid />
    </>
  );
};

export default Intro;
